title: "MedStudyeasy"
description: "MBBS Notes, PYQs & AI Tutor Blog"
theme: minima
author: "MedStudyeasy Team"

# Optional (for blog navigation)
paginate: 5
paginate_path: "/blog/page:num/"
title: "MedStudyeasy"
description: "MBBS Notes, PYQs & AI Tutor Blog"
theme: minima

# Navigation menu
header_pages:
  - index.md
  - blog.md
